### PR TITLE
Add skeleton for rolling support

### PR DESCRIPTION
**Pull request by embeddedadam**
Hello :)
I find your work very useful. I am developing nav2 packages and want to make use of your great tools. I need support for rolling which is not supported yet. Please provide the list of the things that needs to be done to make this work. I was able to build this image and push it to my own docker hub, then locally use it as base in vscode_ros2_workspace.

### CODE REVIEW

**Comment by athackst** [comment]
This looks great!  You should just need to run the `generate.py` script locally to make all of the necessary changes then commit the changes in your PR.

**Comment by embeddedadam** [comment]
Great, I've pushed the changes. Now I think, make sure to upload the image to your docker hub and we can take care of changes in the vscode_ros2_workspace. Thank you for the guidance. :)

**Comment by athackst** [comment]
It should automatically push to docker hub after it merges. 🙂

**Comment by embeddedadam** [comment]
Great, thanks for help :)

**Pull request merged**
