### PR TITLE
Add jazzy to dockerfiles

### LINKED ISSUE #456: Add support for Jazzy
As mentioned in the title, it would be really great to have jazzy images, and from what I can see it seems relatively simple to add support for it.

If you are okay with it, I can open up a MR to add support for it :smile:

### PR DESCRIPTION
**Pull request by athackst**
It doesn't look like there's a [cuda image](https://hub.docker.com/r/nvidia/cuda/tags?page=&page_size=&ordering=&name=) for 24.04 

Ubuntu 24.04 now comes with an "ubuntu" user on 1000:1000 as the nonroot user.  This PR deletes that user in favor of the "ros" user to match previous images.

Closes #456

### CODE REVIEW

**Comment by jncfa** [comment]
One thing, the ubuntu 22.04 docker now has a default user ubuntu with GID 1000, which is why the CI is failing
https://bugs.launchpad.net/cloud-images/+bug/2005129

I opted to delete the user on the image with `userdel -r ubuntu`

**Comment by athackst** [comment]
Thanks! 

I'm considering removing the part that adds a non-root user to the image - but it feels like too big of a change for this.

**Comment by jncfa** [comment]
Wouldn't that cause issues with users of your vscode_workspace_ros2?
I see a bunch of references to a "Ros" user or its home folder 😕

**Comment by athackst** [comment]
There's not that many.  Maybe 3 total?  I'm punting on that for now anyway.  This change should build the jammy image with the ros user instead.

**Comment by jncfa** [comment]
> There's not that many. Maybe 3 total? I'm punting on that for now anyway. This change should build the jammy image with the ros user instead.

Sounds good, just thought I should bring up that up

Thank you for all your hard work on these projects!  😄

**Pull request merged**
